name: Deployment Workflow
on: [push, workflow_dispatch]
jobs: 
  test-code-job:
    runs-on: ubuntu-latest
    steps:
      - name: copying the code
        uses: actions/checkout@v5
      - name: install node-js
        uses: actions/setup-node@v5
        with: 
         node-version: 20.19.5
      - name: check node version
        run: node -v
  build-code-job:
    runs-on: ubuntu-latest
    steps:
      - name: copying the code
        uses: actions/checkout@v5
      - name: install node-js
        uses: actions/setup-node@v5
        with: 
         node-version: 20.19.5
      - name: build project
        run: npm build
  
         